#! /usr/bin/ruby

time = Time.utc 2012, 1, 1
game = 1
last_bet = 0

dir = File.join(ARGV[0],'**','*.txt')
Dir.glob(dir).each do |file| 
  puts "file is #{file}"
  out_file = file.sub(/^\w+\//,'results/').sub(/.txt/,"_fulltilt.txt")
  puts "output file is #{out_file}"

  dir = File.dirname(out_file) 
  root_dir = File.dirname(dir)
  Dir.mkdir(root_dir) unless File.exists?(root_dir)
  Dir.mkdir(dir) unless File.exists?(dir)

  File.open(out_file,'w') do |results|

    lines = File.new(file).readlines
    lines = lines[1..-1]
    dealt = 0

    lines.each do |line|
      if match = /Hand #(\d+)/.match(line)
         results << "FullTiltPoker Game \##{game}: Table Gateway (2 max) - $1/$2 - No Limit Hold'em - #{time.strftime('%H:%M:%S ET - %Y/%m/%d')}\n"
         time += 1
         game += 1
      else 
        if match = /(\: \w+ )([0-9-]+)/.match(line) 
          stack = match[2].to_i + 1000000
          line.sub! /( \(\w+\))(: \w+ )([0-9-]+)/, '\2' + "($#{stack})" 
        end
        if match = /[bets|raises to] ([0-9]+)/.match(line)
          puts "bet is #{match[1]}"
          last_bet = match[1]
        end
        if match = /calls/.match(line)
          puts "adding #{last_bet} to line"
          line.strip!
          line += " $#{last_bet}"
        end
        line.sub! /( |\()([0-9-]+)/, '\1$\2' if line =~ /bets|posts|raises|(wins the pot)|returned/
        line.sub! /shows (.. ..)/, 'shows [\1]' 
        results << line.strip + "\n" 
        if /posts the blind of \$2/.match(line) 
          results << "The button is in seat \#1\n"
          results << "*** HOLE CARDS ***\n"
        end
      end
    end
  end
end

